name: gha-honeymarker-integration
on:
  push:
  schedule:
    - cron: "*/15 * * * *"

jobs:
  integration:
    name: gha-honeymarker-integration
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create honeymarker
        uses: ./
        with:
          apikey: ${{ secrets.BUILDEVENTS_APIKEY }}
          dataset: builds
